name: features_currency
description: "Фича работы с курсами валют и конвертацией."
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  expense_tracker_app:
    path: ../app

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

