name: sync_api
description: Моковые реализации SyncClient и SyncService.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  data_core:
    path: ../data_core
  shared_models:
    path: ../shared_models

dev_dependencies:
  lints: ^3.0.0

